version: '3.6'

services:
  proxy:
    image: nginx:1.17.10
    restart: always
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - lgrapplications-network

networks:
  lgrapplications-network:
    driver: bridge



